# Generated by Django 2.1.7 on 2019-03-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'M'), ('female', 'F')], default='Man', max_length=32),
        ),
    ]
