# Generated by Django 2.1.7 on 2019-04-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190401_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['c_time'], 'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='createTime',
            new_name='c_time',
        ),
    ]
